version: "3.9"
services:
  db:
    image: postgres:15
    container_name: petfinder_db
    environment:
      POSTGRES_DB: petfinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: petfinder_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data:
